from __future__ import annotations

from ..schemas import FileRole, RuleMetadata, Severity


RULE_METADATA: list[RuleMetadata] = [
    RuleMetadata(
        rule_id="LOW_SEARCHABLE_TEXT",
        name="Low Searchable Text",
        description="Flags pages with too little searchable text for reliable automated review.",
        discipline="Document Control",
        default_severity=Severity.INFO,
        default_confidence=0.95,
        profiles=["balanced", "conservative", "aggressive"],
        false_positive_notes="Some drawing cover sheets and image-heavy maps may legitimately have little text.",
    ),
    RuleMetadata(
        rule_id="RASTER_ONLY_PAGE",
        name="Raster Or Scan-Like Page",
        description="Flags pages that appear image-heavy and may need OCR before review.",
        discipline="Document Control",
        default_severity=Severity.INFO,
        default_confidence=0.95,
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="GARBLED_OCR_TEXT",
        name="Possible Garbled OCR",
        description="Flags pages where extracted text contains unusual characters or low-quality OCR.",
        discipline="Document Control",
        default_severity=Severity.MINOR,
        default_confidence=0.80,
        profiles=["balanced", "aggressive"],
    ),
    RuleMetadata(
        rule_id="DRAWING_INDEX_RECONCILIATION",
        name="Drawing Index Reconciliation",
        description="Compares detected sheets against the drawing index reference file.",
        discipline="CAD / Document Control",
        default_severity=Severity.MAJOR,
        default_confidence=0.90,
        required_inputs=[FileRole.DRAWING_INDEX],
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="TITLE_BLOCK_MISSING_FIELD",
        name="Missing Title Block Field",
        description="Checks extracted title block regions for missing required fields.",
        discipline="CAD / Document Control",
        default_severity=Severity.MINOR,
        default_confidence=0.75,
        profiles=["balanced", "aggressive"],
        false_positive_notes="Title block crop regions must be tuned per client/company template.",
    ),
    RuleMetadata(
        rule_id="DUPLICATE_SHEET_NUMBER",
        name="Duplicate Sheet Number",
        description="Flags sheet numbers detected on more than one PDF page.",
        discipline="CAD / Document Control",
        default_severity=Severity.MAJOR,
        default_confidence=0.90,
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="REVISION_MISMATCH",
        name="Revision Mismatch",
        description="Compares title block revision text against the drawing index.",
        discipline="CAD / Document Control",
        default_severity=Severity.MAJOR,
        default_confidence=0.80,
        required_inputs=[FileRole.DRAWING_INDEX],
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="SHEET_TITLE_MISMATCH",
        name="Sheet Title Mismatch",
        description="Compares extracted sheet title text against the drawing index.",
        discipline="CAD / Document Control",
        default_severity=Severity.MINOR,
        default_confidence=0.70,
        required_inputs=[FileRole.DRAWING_INDEX],
        profiles=["balanced", "aggressive"],
    ),
    RuleMetadata(
        rule_id="VALVE_TAG_RECONCILIATION",
        name="Valve Tag Reconciliation",
        description="Compares valve tags found in drawing text against the valve list.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.85,
        required_inputs=[FileRole.VALVE_LIST],
        profiles=["balanced", "conservative", "aggressive", "regulator_station", "p_and_id"],
    ),
    RuleMetadata(
        rule_id="LINE_NUMBER_RECONCILIATION",
        name="Line Number Reconciliation",
        description="Compares line numbers found in drawing text against the line list.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.85,
        required_inputs=[FileRole.LINE_LIST],
        profiles=["balanced", "conservative", "aggressive", "pipeline_crossing"],
    ),
    RuleMetadata(
        rule_id="INSTRUMENT_TAG_RECONCILIATION",
        name="Instrument Tag Reconciliation",
        description="Compares instrument tags found in drawing text against the instrument index.",
        discipline="I&C",
        default_severity=Severity.MAJOR,
        default_confidence=0.85,
        required_inputs=[FileRole.INSTRUMENT_INDEX],
        profiles=["balanced", "conservative", "aggressive", "p_and_id"],
    ),
    RuleMetadata(
        rule_id="EQUIPMENT_TAG_RECONCILIATION",
        name="Equipment Tag Reconciliation",
        description="Compares equipment tags found in drawing text against the equipment list.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.80,
        required_inputs=[FileRole.EQUIPMENT_LIST],
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="PRESSURE_CONSISTENCY",
        name="MAOP And Design Pressure Consistency",
        description="Flags multiple pressure values found for the same pressure label.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.80,
        profiles=["balanced", "conservative", "aggressive", "p_and_id"],
    ),
    RuleMetadata(
        rule_id="CODE_CONSISTENCY",
        name="ASME Code Consistency",
        description="Flags multiple ASME B31 code references in the same drawing set.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.80,
        profiles=["balanced", "conservative", "aggressive"],
    ),
    RuleMetadata(
        rule_id="TEST_PRESSURE_CHECK",
        name="Test Pressure Consistency",
        description="Flags multiple test pressure values found in drawing notes.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.70,
        profiles=["balanced", "aggressive"],
    ),
    RuleMetadata(
        rule_id="MATERIAL_SPEC_CHECK",
        name="Material And Spec Review",
        description="Flags pages with multiple material or pipe specification references.",
        discipline="Mechanical",
        default_severity=Severity.MINOR,
        default_confidence=0.65,
        profiles=["balanced", "aggressive", "pipeline_crossing"],
    ),
    RuleMetadata(
        rule_id="COATING_NOTE_CHECK",
        name="Coating And CP Note Review",
        description="Flags coating and cathodic protection note terms for reviewer verification.",
        discipline="Mechanical / Corrosion",
        default_severity=Severity.MINOR,
        default_confidence=0.65,
        profiles=["aggressive", "pipeline_crossing"],
    ),
    RuleMetadata(
        rule_id="REGULATOR_STATION_CHECKLIST",
        name="Regulator Station Checklist",
        description="Checks for common regulator station terms once regulator-station content is detected.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.70,
        profiles=["regulator_station", "balanced", "aggressive"],
        false_positive_notes="Checklist rules are advisory and should be tuned to company/client standards.",
    ),
    RuleMetadata(
        rule_id="RELIEF_VENT_CHECKLIST",
        name="Relief And Vent Checklist",
        description="Flags relief, vent, and blowdown content that may lack obvious detail references.",
        discipline="Mechanical",
        default_severity=Severity.MAJOR,
        default_confidence=0.75,
        profiles=["regulator_station", "balanced", "aggressive"],
    ),
    RuleMetadata(
        rule_id="TIE_IN_CHECKLIST",
        name="Tie-In Checklist",
        description="Checks tie-in callouts for nearby construction, purge, blowdown, and test-boundary context.",
        discipline="Mechanical / Construction",
        default_severity=Severity.MAJOR,
        default_confidence=0.75,
        profiles=["balanced", "aggressive", "pipeline_crossing"],
    ),
    RuleMetadata(
        rule_id="DETAIL_REFERENCE_CHECK",
        name="Detail Reference Target Sheet",
        description="Flags detail callouts whose target sheet was not detected in the drawing set.",
        discipline="CAD / Design",
        default_severity=Severity.MAJOR,
        default_confidence=0.90,
        profiles=["balanced", "conservative", "aggressive", "pipeline_crossing"],
    ),
    RuleMetadata(
        rule_id="SECTION_REFERENCE_CHECK",
        name="Section Reference Target Sheet",
        description="Flags section callouts whose target sheet was not detected in the drawing set.",
        discipline="CAD / Design",
        default_severity=Severity.MINOR,
        default_confidence=0.85,
        profiles=["balanced", "aggressive"],
    ),
    RuleMetadata(
        rule_id="REPEATED_TAG_REVIEW",
        name="Repeated Tag Review",
        description="Flags tags that appear across many sheets for possible duplicate-tag review.",
        discipline="General",
        default_severity=Severity.INFO,
        default_confidence=0.55,
        profiles=["aggressive"],
    ),
    RuleMetadata(
        rule_id="COMMENT_QUALITY_SCORER",
        name="Comment Quality Scorer",
        description="Reserved for future deterministic comment-quality checks.",
        discipline="QA",
        default_severity=Severity.INFO,
        default_confidence=0.65,
        enabled_by_default=False,
        profiles=[],
    ),
    RuleMetadata(
        rule_id="RFI_CANDIDATE_DETECTOR",
        name="RFI Candidate Detector",
        description="Classifies existing findings as likely RFI candidates based on deterministic keywords.",
        discipline="Project Management",
        default_severity=Severity.MAJOR,
        default_confidence=0.65,
        profiles=["balanced", "aggressive"],
        output_type="classification",
    ),
    RuleMetadata(
        rule_id="AI_COMMENT_DRAFTS",
        name="AI Comment Draft Hook",
        description="Optional future hook for comment rewriting. Disabled by default.",
        discipline="QA",
        default_severity=Severity.INFO,
        default_confidence=0.50,
        enabled_by_default=False,
        profiles=[],
        output_type="extension_hook",
    ),
    RuleMetadata(
        rule_id="SYMBOL_RECOGNITION_STUB",
        name="Symbol Recognition Hook",
        description="Optional future hook for validated computer-vision counting. Disabled by default.",
        discipline="QA",
        default_severity=Severity.INFO,
        default_confidence=0.40,
        enabled_by_default=False,
        profiles=[],
        output_type="extension_hook",
    ),
    RuleMetadata(
        rule_id="ASSET_REGISTER_DRAFT",
        name="Asset Register Draft",
        description="Creates support exports from deterministic tag extraction.",
        discipline="Operations",
        default_severity=Severity.INFO,
        default_confidence=0.50,
        profiles=["balanced", "aggressive"],
        output_type="support_export",
    ),
]


RULE_METADATA_BY_ID: dict[str, RuleMetadata] = {item.rule_id: item for item in RULE_METADATA}


def get_rule_metadata() -> list[RuleMetadata]:
    return list(RULE_METADATA)
